### ISSUE TITLE
Error occurs when doing Prune invisible Faces

### ISSUE THREAD

**Issue by DTMination** [CazzoPMX/KKPMX#32]
When I do All in one, the terminal suddenly crushed when it running a certain step. It seems like Prune invisible Faces crushes the application. Could you please check it? Thx.

The error log is as following:

Traceback (most recent call last):
  File "kkpmx_core.py", line 2032, in <module>
  File "kkpmx_core.py", line 133, in main
  File "kkpmx_core.py", line 717, in kk_quick_convert
  File "kkpmx_core.py", line 1454, in delete_invisible_faces
IndexError: index 512 is out of bounds for axis 1 with size 512

**Comment by CazzoPMX** [comment]
Should be fixed with v 2.4.1
