### ISSUE TITLE
Error occurs when doing Final Cleanup over the whole model

### ISSUE THREAD

**Issue by DTMination** [CazzoPMX/KKPMX#33]
In All-in-One sequence, when terminal executes the "Final Cleanup over the whole model" it crashed. The Error Log is as follows:
```
Traceback (most recent call last):
  File "kkpmx_core.py", line 2036, in <module>
  File "kkpmx_core.py", line 133, in main
  File "kkpmx_core.py", line 777, in kk_quick_convert
  File "kkpmx_special.py", line 294, in simplify_armature
  File "kkpmx_utils.py", line 515, in find_all_in_sublist
  File "kkpmx_utils.py", line 427, in contains
  File "re.py", line 200, in search
  File "re.py", line 303, in _compile
  File "sre_compile.py", line 764, in compile
  File "sre_parse.py", line 948, in parse
  File "sre_parse.py", line 443, in _parse_sub
  File "sre_parse.py", line 668, in _parse
re.error: nothing to repeat at position 0
```
Also, the last frame before crashed is pasted here:
![image](https://github.com/CazzoPMX/KKPMX/assets/62316089/4a86bce0-f600-4393-8d9d-fc06c1b1cefc)

**Comment by DTMination** [comment]
Thanks to Cazzo, this issue has been solved in releases 3.0.2.
